dist: xenial
language: python
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-test.txt
script:
  - coverage run -m unittest *.py
  - flake8 .
after_success:
  - codecov

matrix:
  include:
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'